### PR TITLE
Very minor spelling correction

### PR DESCRIPTION
**Pull request by Nieuwlaar**

### CODE REVIEW

**Review by digeorgi — APPROVED** [review]

**Review by pinamiranda — COMMENTED** [review]
Change not accepted.

Section 4.2.2  defines four distinct communication flows between a Wallet Instance and a Relying Party.

Specific use cases need to integrate one or more of these flows. So, the use of “may” in this context implies that integrating one or more of the flows is optional, but in reality, it is a necessary requirement for specific use cases.

**Comment by david-bakker** [comment]
Good point, @pinamiranda ! Indeed my earlier answer to Stavros was incorrect; each use case always must use one or more of these flows. Thanks for being sharp :-).

**Comment by Nieuwlaar** [comment]
Clear. How about adding 'must' for clarity? (I updated this PR accordingly)

**Comment by pinamiranda** [comment]
@Nieuwlaar , probably we should use "shall" instead of "must". @david-bakker , do you agree?

For context, in my opinion, “shall” is typically used in legal or formal documents to indicate a requirement or obligation, while “must” is often used in general contexts to express necessity or obligation.

**Comment by pinamiranda** [comment]
Ok @david-bakker , you're right. Thank you

**Review by pinamiranda — APPROVED** [review]
change approved

**Comment by skounis** [comment]
@pinamiranda From your reply to @david-bakker I understand that you agree with his position that we should not change the text, so we do not add the `must` word in the sentence. 

After this however you approved this PR which introduces the addition of the work `must`. Something that contradicts the previous. 

Could you please clarify? Should we keep the text as it is and ignore this PR or should we merge it and add the word `must` in the text?

**Comment by pinamiranda** [comment]
@skounis I understand that @david-bakker mentioned that ‘must’ was acceptable and we should not change it to ‘shall’ (as ‘shall’ could be interpreted as a requirement). Since my question was about using ‘must’ or ‘shall’, I agreed with @david-bakker that ‘must’ was the best option, and I approved the change.

**Comment by skounis** [comment]
> In general I agree. However, regarding this specific document there is another aspect: we agreed to not include any requirements in the ARF main document. Requirements should go only in Annex 2. So actually I think the sentence is perfect as it is and we should not change it.
> 
> Sorry about not remembering this earlier...

@pinamiranda My understanding here is that @david-bakker suggests to keep the sentence as it is. So we do not apply the only change the PR suggest 

image


cc @david-bakker

**Comment by david-bakker** [comment]
Hi both, sorry about the confusion! I indeed meant to say that we use neither 'shall' nor 'must' in the ARF main document, because it only states facts. So, as Stavros says, we should not accept the PR.

**Pull request closed without merging**
