### PR TITLE
Minor ortography fixes

### PR DESCRIPTION
**Pull request by joelposti**
Minor ortography fixes for the ARF and the annexes. Fixes are split into multiple commits and each commit has an explanatory comment.

One of the changes is in `docs/media/image7.svg` (replaced ‘EUDI Wallet instance’ with ‘EUDI Wallet Instance’). It looks like the related file `docs/media/image7.png` already has the latter ortography and thus no changes for that file is needed.

### CODE REVIEW

**Review by skounis — DISMISSED** [review]

**Review by duviner — DISMISSED** [review]

**Comment by joelposti** [comment]
I pushed some additional orthography fixes. Should I create a new pull request or keep the commits in this one?

**Comment by skounis** [comment]
Process wise the review already started so new commits will make it more difficult. On top of this the PR has already approved by two reviewers before the new commits. 

However I checked the commits one by one and my positive vote remains unchanged ;-)

**Comment by joelposti** [comment]
Okay, thank you for your patience. I am sorry that I deviated from the process. I should have asked first before pushing new commits.

**Review by paolo-de-rosa — DISMISSED** [review]

**Comment by pinamiranda** [comment]
Thank you for submitting the Pull Request.

We have reviewed ARF 1.4, and all the minor ortography issues have been fixed (or will be fixed in ARF 1.4.1)

**Review by skounis — COMMENTED** [review]
The incoming branch needs to be rebased

**Review by duviner — DISMISSED** [review]

**Comment by joelposti** [comment]
@skounis, thanks for making a new PR! I was on summer vacation when you asked to rebase the branch.

**Review by digeorgi — COMMENTED** [review]
Thoroughly reviewed and approved.

**Pull request closed without merging**
