### PR TITLE
Vrk kpa minor ortography fixes 2024 03 11

### PR DESCRIPTION
**Pull request by skounis**
As per
* https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/pull/134#pullrequestreview-2147412391
* https://github.com/vrk-kpa/eudi-doc-architecture-and-reference-framework/pull/1

This PR brings a rebased version of @vrk-kpa [branch ](https://github.com/vrk-kpa/eudi-doc-architecture-and-reference-framework/tree/minor-ortography-fixes-2024-03-11) and [PR](https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/pull/134)

### CODE REVIEW

**Comment by joelposti** [comment]
@skounis, thanks for making a new PR! I was on summer vacation when you asked to rebase the branch of my pull request.

**Review by digeorgi — APPROVED** [review]
Reviewed and approved

**Review by digeorgi — APPROVED** [review]
Changes reviewed approves.

**Review by pinamiranda — APPROVED** [review]
Reviewed

**Pull request merged**
