### PR TITLE
Gender pronoun fixes

### PR DESCRIPTION
**Pull request by joelposti**
Consistent usage of ‘he/she’, ‘his/her’ and ‘him/her’.

Another option is to replace gendered pronouns with ‘they’, ‘their’ and ‘them’.

### CODE REVIEW

**Comment by skounis** [comment]
I support the suggestion however I'm in favor of "they" due to

> Using "they" is generally considered more inclusive and gender-neutral compared to "he/she." It avoids assuming someone's gender and is widely accepted in contemporary writing.

**Comment by pinamiranda** [comment]
Thank you for submitting the Pull Request.

We have reviewed sections arf.md in ARF 1.4, and all gender pronouns have been fixed.

docs/annexes/annex-09-design-guide-data-sharing-scenarios.md is now docs/annexes/annex-5/annex-5.02-design-guide-data-sharing-scenarios.pdf and it will be reviewed in order to fix the gender pronouns.

**Review by duviner — APPROVED** [review]

**Review by skounis — CHANGES_REQUESTED** [review]
The incoming branch needs to be rebased, similar to https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/pull/134#pullrequestreview-2147412391

**Review by digeorgi — DISMISSED** [review]
Review performed.

**Comment by joelposti** [comment]
@skounis, I will rebase the branch this week.

**Comment by joelposti** [comment]
@skounis I rebased the branch. Most of the gendered pronouns had been removed from the current version of ARF and its annexes. There were just one ‘his’ and one ‘him’ left. I replaced those with gender neutral ‘their’ and ‘them’ as that suggestion got a favourable reception.

**Review by digeorgi — APPROVED** [review]
Proposed changes reviewed and approved.

**Review by skounis — APPROVED** [review]

**Review by pinamiranda — COMMENTED** [review]
Reviewed

**Pull request merged**
